version: '3.8'

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/data/db
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/data/wordpress

networks:
  app-network:

services:
  nginx:
    image: nginx:iabkadri
    build:
      context: requirements/nginx
    container_name: nginx
    env_file:
      - .env
    ports:
      - 443:443
    restart: unless-stopped
    depends_on:
      - wordpress
        #condition: service_healthy
    volumes:
      - wordpress:/var/www/html
    networks:
      - app-network
  
  wordpress:
    image: wordpress:iabkadri
    build:
      context: requirements/wordpress
    container_name: wordpress
    env_file:
      - .env
    restart: unless-stopped
    #healthcheck:
    #  #mysqladmin ping -h"$DB_HOST" --silent
    #  test: [ "CMD", "mariadb-admin",  "ping", "-h", "mariadb", "--silent" ]
    #  interval: 3s
    #  retries: 4
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    networks:
      - app-network

  mariadb:
    image: mariadb:iabkadri
    build:
      context: requirements/mariadb
    container_name: mariadb
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql
    networks:
      - app-network
