version: '3.7'

volumes:
  db:
  wordpress:

networks:
  app-network:

services:
  nginx:
    build:
      context: requirements/nginx
    container_name: nginx
    env_file:
      - .env
    ports:
      - 443:443
    restart: unless-stopped
    healthcheck:
      test: CMD [ "ping", "wordpress" ] || exit 1
      interval: 3s
      retries: 3
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - app-network
  
  wordpress:
    build:
      context: requirements/wordpress
    container_name: wordpress
    environment:
      - MYSQL_HOST=mariadb:3306
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: CMD [ "ping", "mariadb" ] || exit 1
      interval: 3s
      retries: 3
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    networks:
      - app-network

  mariadb:
    build:
      context: requirements/mariadb
    container_name: mariadb
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql
    networks:
      - app-network
