version: '3'

networks:
  app-network:

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '/home/essam/data'
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '/home/essam/data'

services:
  nginx:
    build:
      context: ./requirements/nginx/
    command: nginx -g 'daemon off;'
    container_name: nginx
    depends_on:
      - wordpress
    #healthcheck:
    #  test: ["nc", "wordpress", "9000"]
    ports:
      - 443:443
    volumes:
      - /home/essam/data/wordpress:/var/www/html
    networks:
      - app-network

  mariadb:
    build:
      context: ./requirements/mariadb/
    container_name: mariadb
    restart: on-failure
    env_file: .env
    expose:
      - "3306"
    volumes:
      - /home/essam/data/db:/var/lib/mysql
    networks:
      - app-network

  wordpress:
    build:
      context: ./requirements/wordpress/
    container_name: wordpress
    depends_on:
      - mariadb
    restart: on-failure
    env_file: .env
    volumes:
      - /home/essam/data/wordpress:/var/www/html
    networks:
      - app-network
